# build and push builded images

- hosts: local
  become: true

  vars_files:
    - "vars/env.yml"


  post_tasks:
    - name: Restart docker
      command: systemctl reload docker

  roles:
    - deploy-local-conf-docker


- hosts: centoscible
  become: true

  roles:
    - docker-deploy-registry

