---
- name: Install all dependencies python
  yum:
   name: "{{ item }}"
   #update_cache: true
   state: present
  with_items:
    - python-dev
    - python3-dev
    - libsasl2-dev
    - python-dev
    - libldap2-dev
    - libssl-dev
    - python3-pip
    - python-pip
    - git
    - python-docker



- name: install (Bottle) python package.
  pip:
    name: docker-py
