---
- name: Build fake-backend image and push on personal DockerHub
  docker_image:
    path: /fake-backend/
    name: samiamr/fake-backend
    push: yes
    tag: 1.0

- name: Create docker network
  docker_network:
    name: battleboat

- name: Create a volume db-data
  docker_volume:
    name: db-data

- name: Create volumes folders fo bind option
  file:
    path: /etc/volumes/ {{ item }}
    state: directory
  with_items:
    - battleboat-gh-pages

- name: Git clone project fack-backend
  git:
    repo: 'https://github.com/billmei/battleboat.git'
    dest: /etc/volumes/battleboat-gh-pages
    force: yes
    recursive: no

#- name: Push html webapp file for testing
#  copy:
#    src: files/battleboat/
#    dest: /etc/VOLUMES/battleboat-gh-pages
#    mode: 0644
