---
- name: Deploy Database container
  docker_container:
    name: db-samiamr
    hostname: db-samiamr
    image: mysql:5.7
    state: started
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - name: battleboat
    ports:
      - "3306:3306"
    restart_policy: "always"
    env:
      MYSQL_ROOT_PASSWORD: "root-samiamr"
      MYSQL_DATABASE: "battleboat"
      MYSQL_USER: "battleuser"
      MYSQL_PASSWORD: "battlepass"

- name: "Deploy fake-backend container"
  docker_container:
    name: battle-samiamr
    hostname: battle-samiamr
    image: samiamr/fake-backend:1.0
    state: started
    volumes:
     - /etc/volumes/battleboat-gh-pages:/etc/backend/static
    networks:
      - name: battleboat
    ports:
      - "8181:3000"
    restart_policy: "always"
    env:
      DATABASE_HOST: "db-samiamr"
      DATABASE_PORT: "3306"
      DATABASE_USER: "battleuser"
      DATABASE_PASSWORD: "battlepass"
      DATABASE_NAME: "battleboat"
